dist: bionic
matrix:
  include:
  - name: "Git use and project structure"
    language: bash
    os: linux
    script:
    - bash ./test/git_use.sh

  - name: "R code tests"
    language: r 
    os: linux
    before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
    script:
    - Rscript ./test/test.R
