dist: bionic
matrix:
  include:
  - name: "Git use and project structure"
    language: bash
    os: linux
    script:
    - bash ./test/git_use.sh
    

  - name: "Python code tests"
    language: python 
    os: linux
    before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    #- "export PYTHONPATH=$PYTHONPATH:$(pwd)" # based on solution 1 of https://stackoverflow.com/questions/35972415/python-import-fails-on-travisci-but-not-locally

    
    install:
    - wget https://raw.githubusercontent.com/GeoScripting-WUR/InstallLinuxScript/master/user/environment.yml
    - conda env create -f environment.yml
    #- conda create --name geoscripting --file SetUpCondaEnv.txt
    #- pip install fiona==1.8.8 geopandas rasterio rasterstats  
    - conda activate geoscripting
        
    script:
    - python --version
    - python -c "import fiona; print(fiona.__version__)"
    - python -m Main
    - python -c "import sys; print('\n'.join(sys.path)); import os; print(os.getcwd())"
    - python -m test.Test_VectorExercise

notifications:
  webhooks: https://outlook.office.com/webhook/6def7055-83f3-4675-b277-292d8b99b9b7@27d137e5-761f-4dc1-af88-d26430abb18f/TravisCI/5c0c169a79414da59908577fd8454920/95bfbb24-83a4-44d4-b55d-c765e79f211f
